### ISSUE TITLE
Argument T_ARG_INT conversion error to signed 32bits (int) instead of unsigned 32bits (uint32_t)

### ISSUE THREAD

**Issue by bvernoux** [biot/tokenline#3]
See patch [fix_T_ARG_INT.patch](https://gist.github.com/bvernoux/225e36f0178a8f0ab743)

**Comment by bvernoux** [comment]
See pull request "Fixed T_ARG_INT to unsigned integer value (32bits) and updated README" #4

**Comment by biot** [comment]
Merged with some changes, thanks!
